opt_out_usage # Disable metrics collection
default_platform(:android)

platform :android do
  desc "Build APK. Accepts build_type option (default: Debug). Keystore is only used for Release builds."
  lane :build do |options|
    build_type = (options[:build_type] || "Debug").capitalize

    gradle_options = {
      task: "assemble",
      build_type: build_type,
      flags: "--stacktrace",
      print_command: false,
      gradle_path: "fastlane/gradlew",
    }

    if build_type == "Release"
      gradle_options[:properties] = {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"],
      }
    end

    gradle(**gradle_options)

    next unless ENV["GITHUB_OUTPUT"]

    tags = sh("git tag --list 'v[0-9]*'", log: false).strip.split("\n").reject(&:empty?)
    version_code = [tags.size, 1].max
    File.open(ENV["GITHUB_OUTPUT"], "a") do |f|
      f.puts "version_code=#{version_code}"
      changelog_file = "fastlane/metadata/android/en-US/changelogs/#{version_code}.txt"
      if File.exist?(changelog_file)
        f.puts "body<<CHANGELOG_EOF"
        f.puts File.read(changelog_file).strip
        f.puts "CHANGELOG_EOF"
      end
    end
  end
end
